name: piapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  google_fonts: ^5.0.0
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.0
  

flutter:
  uses-material-design: true
  
  
  assets:
   - Images/Women brainstorming ideas and working in team (1).png
   - Images/image 6.png
   - Images/Work team brainstorming in conference room (1).png
   - Images/Dreaming about future occupation (1).png
   - Images/logo 2.png
   - Images/image 13 (1).png
   - Images/Clock (1).png
   - Images/Instagram (2).png
   - Images/Vector 1.png
   - Images/Vector 2.png

   
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
